### ISSUE TITLE
TypeError: 'errors' is an invalid keyword argument for this function

### ISSUE THREAD

**Issue by johnjohnsp1** [mdsecactivebreach/PowerDNS#1]
Hello, thanks for sharing the tool, actually I get this error once i type: python powerdns.py -h 

~/PowerDNS# python powerdns.py -h
Traceback (most recent call last):
  File "powerdns.py", line 6, in <module>
    from scapy.all import *
  File "/usr/local/lib/python2.7/dist-packages/scapy/all.py", line 10, in <module>
    from .config import *
  File "/usr/local/lib/python2.7/dist-packages/scapy/config.py", line 11, in <module>
    from .data import *
  File "/usr/local/lib/python2.7/dist-packages/scapy/data.py", line 184, in <module>
    TCP_SERVICES,UDP_SERVICES=load_services("/etc/services")
  File "/usr/local/lib/python2.7/dist-packages/scapy/data.py", line 109, in load_services
    f=open(filename, errors='ignore')
TypeError: 'errors' is an invalid keyword argument for this function

I'm using kali linux as distro with VMware Fusion on OS X Sierra 10.12.5 -
Linux 2017 4.9.0-kali4-amd64 #1 SMP Debian 4.9.30-2kali1 (2017-06-22) x86_64 GNU/Linux
python version is 2.7.13

thanks

**Comment by dmchell** [comment]
I'm unable to reproduce this...
root@kali:~/Tools/PowerDNS# python --version
Python 2.7.13
root@kali:~/Tools/PowerDNS# uname -a
Linux kali 4.9.0-kali4-amd64 #1 SMP Debian 4.9.30-1kali1 (2017-06-06) x86_64 GNU/Linux
root@kali:~/Tools/PowerDNS# python powerdns.py -h
___                        ___  _ _  ___
| . \ ___  _ _ _  ___  _ _ | . \| \ |/ __>
|  _// . \| | | |/ ._>| '_>| | ||   |\__ \
|_|  \___/|__/_/ \___.|_|  |___/|_\_|<___/

@domchell, MDSec ActiveBreach

usage: powerdns.py [-h] [--file <file>] [--domain <domain>]

optional arguments:
  -h, --help         show this help message and exit
  --file <file>      PowerShell file to serve
  --domain <domain>  Domain with auth NS record
root@kali:~/Tools/PowerDNS#

It appears to be related to the scapy package you have, can you make sure you're up to date? It's working with python-scapy 2.3.3-1.

**Comment by johnjohnsp1** [comment]
thanks for the reply, checked the scapy version but its the same as yours:

~# apt-get install python-scapy
Lettura elenco dei pacchetti... Fatto
Generazione albero delle dipendenze       
Lettura informazioni sullo stato... Fatto
python-scapy is already the newest version (2.3.3-1).
0 aggiornati, 0 installati, 0 da rimuovere e 0 non aggiornati.
~# cd PowerDNS/
~/PowerDNS# python powerdns.py 
Traceback (most recent call last):
  File "powerdns.py", line 6, in <module>
    from scapy.all import *
  File "/usr/local/lib/python2.7/dist-packages/scapy/all.py", line 10, in <module>
    from .config import *
  File "/usr/local/lib/python2.7/dist-packages/scapy/config.py", line 11, in <module>
    from .data import *
  File "/usr/local/lib/python2.7/dist-packages/scapy/data.py", line 184, in <module>
    TCP_SERVICES,UDP_SERVICES=load_services("/etc/services")
  File "/usr/local/lib/python2.7/dist-packages/scapy/data.py", line 109, in load_services
    f=open(filename, errors='ignore')
TypeError: 'errors' is an invalid keyword argument for this function

**Comment by johnjohnsp1** [comment]
i have no idea whats wrong with kali installation but once a test with another distribution like backbox:

Linux backbox 4.4.0-83-generic #106~14.04.1-Ubuntu SMP Mon Jun 26 18:10:19 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
Python 2.7.6
Scapy
INFO: Can't import python gnuplot wrapper . Won't be able to plot.
INFO: Can't import PyX. Won't be able to use psdump() or pdfdump().
WARNING: No route found for IPv6 destination :: (no default route?)
Welcome to Scapy (2.2.0)

~/powerdns# python powerdns.py 
WARNING: No route found for IPv6 destination :: (no default route?)
___                        ___  _ _  ___
| . \ ___  _ _ _  ___  _ _ | . \| \ |/ __>
|  _// . \| | | |/ ._>| '_>| | ||   |\__ \
|_|  \___/|__/_/ \___.|_|  |___/|_\_|<___/

@domchell, MDSec ActiveBreach

[*] PowerDNS: The --file and --domain arguments are required

everything is working.
Suppose your code have no issue but it's something related to anything I probably installed later past setup OS that make me get that error on scapy.

Thanks again for the reply, appreciate your help out there
and of course thanks again for share the code

**Comment by dmchell** [comment]
No problem, glad it's working :)
